version: "3.7"

services:
    fluxcp:
        build: .
        ports:
          - 80:80
        container_name: fluxcp
        volumes:
            - .:/var/www/html
            - ./vhost.conf:/etc/apache2/sites-enabled/vhost.conf
